# Generated by Django 5.1.3 on 2024-11-29 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='student',
            new_name='User',
        ),
    ]
